### ISSUE TITLE
请问可以分享一下涉及到ChatGPT生成的数据吗？

### ISSUE THREAD

**Issue by Maydaytyh** [wuyike2000/CoTKR#1]
非常感谢开源代码:)
我暂时没有办法调用ChatGPT的接口，请问可以分享用到ChatGPT生成的中间文件吗？如Supervised Fine-tuning Corpus Generation、Preference Alignment Corpus Generation和Preference Alignment Ablation Experiment Corpus Generation，谢谢！

**Comment by wuyike2000** [comment]
您好，我们已经将生成的训练数据放在这个链接：https://mega.nz/file/0cA2TZwQ#2oBVW0wILPdZf9IxbQCIlMMjZE3fpi0dqinqAhRuwtc。
README同步进行了更新。

**Comment by Maydaytyh** [comment]
感谢！
